//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCValidation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeValidation
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string Salary { get; set; }
        public string HireDate { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Age { get; set; }
        public string Mobile { get; set; }
    }
}
